server:
  port: 11111
github:
  client:
    clientId: 1c23891103858487501e
    clientSecret: f33376b3bdf95b4c4ef2645b0358b183af8afb42
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

spring:
  jpa:
    database-platform: POSTGRESQL
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: bvvyeh288
    url: jdbc:postgresql://localhost:5432/bvvy_divide2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 1c23891103858487501e
            client-secret: f33376b3bdf95b4c4ef2645b0358b183af8afb42

#  data:
#    elasticsearch:
#      cluster-nodes: 127.0.0.1:9300
#eureka:

#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/