server:
  port: 11111
#security:
#  oauth2:
#    client:
#      client-id: acme
#      client-secret: acmesecret
#      access-token-uri: http://localhost:8901/oauth/token
#      user-authorization-uri: http://localhost:8901/oauth/authorize
#    resource:
#      user-info-uri: http://localhost:8901/me
#Setting the logging levels for the service
#logging:
#  level:
#    com.netflix: WARN
#    org.springframework.web: WARN
#    com.divide2: DEBUG
spring:
  jpa:
    database-platform: POSTGRESQL
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: bvvyeh288
    url: jdbc:postgresql://localhost:5432/bvvy_divide2

#  data:
#    elasticsearch:
#      cluster-nodes: 127.0.0.1:9300
#eureka:

#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/